import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { resolveActiveShellPaths } from '../app-shell-adapter.ts';

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const shellPaths = resolveActiveShellPaths();

export type ReleaseBoundaryCheck = {
  id: string;
  file: string;
  required?: string[];
  forbidden?: string[];
  retired?: boolean;
};

export const releaseWorkflowPaths = [
  '.github/workflows/_build-reusable.yml',
  '.github/workflows/build-manual.yml',
  '.github/workflows/desktop-release-cleanup-drafts.yml',
  '.github/workflows/desktop-release-diagnostics.yml',
  '.github/workflows/desktop-release-promote.yml',
  '.github/workflows/desktop-release.yml',
  '.github/workflows/docker-webui-clean-linux-vm.yml',
  '.github/workflows/docker-webui-clean-windows-vm.yml',
  '.github/workflows/full-first-install-release.yml',
  '.github/workflows/full-runtime-cache-warmup.yml',
  '.github/workflows/homebrew-tap-update.yml',
  '.github/workflows/nightly-standard-release.yml',
  '.github/workflows/non-release-validation.yml',
  '.github/workflows/opl-first-run-vm.yml',
  '.github/workflows/release-verify-remote.yml',
  '.github/workflows/webui-ghcr-release.yml',
];

export const releaseBoundaryChecks: ReleaseBoundaryCheck[] = [
  {
    id: 'retired_build_and_release_workflow_absent',
    file: '.github/workflows/build-and-release.yml',
    retired: true,
  },
  {
    id: 'release_contract_repo',
    file: 'contracts/app-release-channel.json',
    required: ['"release_repo": "gaofeng21cn/one-person-lab-app"'],
    forbidden: ['"release_repo": "gaofeng21cn/one-person-lab"'],
  },
  {
    id: 'publish_script_repo',
    file: 'scripts/publish-release.ts',
    required: ["'gaofeng21cn/one-person-lab-app'"],
    forbidden: ["'gaofeng21cn/one-person-lab'"],
  },
  {
    id: 'update_bridge_repo',
    file: path.relative(appRoot, path.join(shellPaths.shellRoot, 'packages/desktop/src/process/bridge/updateBridge.ts')),
    required: ["'gaofeng21cn/one-person-lab-app'"],
    forbidden: ["const DEFAULT_REPO = 'gaofeng21cn/one-person-lab'"],
  },
  {
    id: 'application_bridge_repo',
    file: path.relative(appRoot, path.join(shellPaths.shellRoot, 'packages/desktop/src/process/bridge/applicationBridgeCore.ts')),
    required: ["'gaofeng21cn/one-person-lab-app'"],
    forbidden: ["|| 'gaofeng21cn/one-person-lab'"],
  },
  {
    id: 'first_run_vm_download_repo',
    file: '.github/workflows/opl-first-run-vm.yml',
    required: [
      '--repo "$GITHUB_REPOSITORY"',
      'One-Person-Lab-Full-*-mac-arm64.dmg',
      'One-Person-Lab-*-mac-arm64.dmg',
      'release_artifact_name:',
      'release_artifact_run_id:',
      'framework_ref:',
      'actions/download-artifact@v8',
      'run-id: ${{ inputs.release_artifact_run_id || github.run_id }}',
      'Using same-run workflow artifact',
      'Using source workflow run artifact',
      'Checkout OPL Framework bootstrap source',
      'repository: gaofeng21cn/one-person-lab',
      'Prepare OPL Framework bootstrap archive',
      'git -C one-person-lab archive --format=tar.gz --prefix=one-person-lab/',
      'CMD+=(--framework-source-archive "${{ steps.framework_source.outputs.archive_path }}")',
      'CMD+=(--framework-install-script "${{ steps.framework_source.outputs.install_script_path }}")',
      'fetch_release_metadata_with_retry()',
      'Release metadata fetch failed on attempt $attempt',
      'download_asset_with_retry()',
      'download_release_with_retry()',
      'Resolved release DMG asset: $asset_name',
      'Release DMG asset download failed on attempt $attempt',
      'asset.apiUrl || asset.url',
      'Accept: application/octet-stream',
      'Authorization: Bearer ${GH_TOKEN}',
      'curl_args=(-fL --retry 5 --retry-all-errors --retry-delay 10 --connect-timeout 30 --max-time 1800 --continue-at -)',
      'fetch-depth: 1',
      'sparse-checkout: scripts',
      'package_profile:',
      'diagnostic_scope:',
      "diagnostic_scope != 'bootstrap_only'",
      'Resolve package profile',
      '--smoke-profile no-clt-clean-vm',
      '--display 1920x1080px',
      '--settings-smoke',
      '--assistant-route-smoke',
      '--codex-functional-check',
      '--codex-ai-self-check',
      '--runtime-profile "${{ steps.package_profile.outputs.runtime_profile }}"',
      'guide_screenshots:',
      'CMD+=(--guide-screenshots)',
    ],
    forbidden: ['--repo gaofeng21cn/one-person-lab'],
  },
  {
    id: 'full_release_workflow_uses_app_scripts',
    file: '.github/workflows/full-first-install-release.yml',
    required: [
      'npm --silent run release:full',
      'npm run release:publish',
      'Inspect optional Full release signing secrets',
      'Full first-install local authorization mode',
      'Missing optional Apple signing secrets:',
      'brew install zstd temporal || true',
      'OPL_FULL_BUN_BIN=$(command -v bun)',
      'OPL_FULL_INCLUDE_BUN_RUNTIME',
      'OPL_FULL_TEMPORAL_CLI_BIN=$(command -v temporal)',
      'Checkout OPL Flow',
      'repository: gaofeng21cn/opl-flow',
      'Validate Full source roots',
      'Required Full source is missing:',
      'export OPL_FULL_OPL_FLOW_ROOT="$GITHUB_WORKSPACE/opl-flow"',
      'export OPL_FULL_BUN_BIN="${OPL_FULL_BUN_BIN:-$(command -v bun)}"',
      'export OPL_FULL_TEMPORAL_CLI_BIN="${OPL_FULL_TEMPORAL_CLI_BIN:-$(command -v temporal)}"',
      'Stable Full assets will use local authorization evidence instead of Developer ID notarization.',
      'full-local-authorization-policy.json',
      'full-runtime-currentness-probe.json',
      'full-runtime-native-trust.json',
      'local-authorization-policy.ts',
      'mounted_app_path="$(find "$mounted_app_dir" -maxdepth 2 -type d -name \'One Person Lab.app\'',
      'codesign --verify --deep --strict --verbose=2 "$mounted_app_path"',
      '--app-path "$mounted_app_path"',
      'spctl --assess --type execute --verbose=4 "$app_path"',
      'Upload Full DMG-only workflow artifact',
      'opl-full-first-install-dmg-${{ env.OPL_RELEASE_VERSION }}-mac-arm64',
      'One-Person-Lab-Full-${{ env.OPL_RELEASE_VERSION }}-mac-arm64.dmg',
      'Prepare Full release notes',
      'GH_TOKEN: ${{ github.token }}',
      'GITHUB_TOKEN: ${{ github.token }}',
      'OPL_RELEASE_NOTES_MODE: ai',
      'OPL_RELEASE_NOTES_PROVIDER: openai_compatible',
      "OPL_RELEASE_NOTES_CODEX_BASE_URL: ${{ vars.OPL_RELEASE_NOTES_CODEX_BASE_URL || 'https://gflabtoken.cn/v1' }}",
      "OPL_RELEASE_NOTES_MODEL: ${{ vars.OPL_RELEASE_NOTES_MODEL || 'gpt-5.4-mini' }}",
      'npm run release:notes:probe-ai',
      'OPL_RELEASE_NOTES_FILE: ${{ runner.temp }}/full-release-notes.md',
      '--release-notes-file "$OPL_RELEASE_NOTES_FILE"',
    ],
    forbidden: [
      'npm run gui:release',
      'packages:full-release',
      'repository: gaofeng21cn/one-person-lab-app',
      'models: read',
      'OPL_RELEASE_NOTES_GITHUB_MODEL',
      '--input "$RUNNER_TEMP/full-release-notes-template.md"',
    ],
  },
  {
    id: 'desktop_release_workflow_uses_app_scripts',
    file: '.github/workflows/desktop-release.yml',
    required: [
      'release-preflight:',
      'name: Release preflight',
      'release_intent:',
      'release_operator_plan_ref:',
      'gate_reuse_plan_ref:',
      '--release-intent "${{ inputs.release_intent }}"',
      '--release-operator-plan-ref "${{ inputs.release_operator_plan_ref }}"',
      '--gate-reuse-plan-ref "${{ inputs.gate_reuse_plan_ref }}"',
      'Generate release:gate-reuse-plan for the same cohort',
      'gh run watch --interval 60',
      'npm run release:preflight --',
      'release-preflight-summary.json',
      'release-preflight-summary.md',
      'release-workflow-contract:',
      'name: Release workflow contract',
      'name: Checkout OPL Flow policy source',
      'repository: gaofeng21cn/opl-flow',
      'ref: 5ae0625f5240a13fa820b4c92362f1d06bdce857',
      'path: opl-flow',
      'OPL_FLOW_WORKFLOW_POLICY: ${{ github.workspace }}/opl-flow/contracts/workflow-policy.json',
      'OPL_FULL_OPL_FLOW_ROOT: ${{ github.workspace }}/opl-flow',
      'npm run test:release-boundary',
      'release-source-gate:',
      'name: Release source gate',
      'npm run release:source-gate --',
      '--app-ref "$GITHUB_SHA"',
      '--shell-ref "${{ inputs.shell_ref || \'main\' }}"',
      '--framework-ref "${{ inputs.framework_ref || \'main\' }}"',
      '--require-shell-format true',
      'cancel-in-progress: false',
      'homebrew_tap_update_required',
      'release-source-gate',
      'uses: ./.github/workflows/_build-reusable.yml',
      'require_macos_gatekeeper: false',
      'name: macos-build-arm64',
      'remote-verify-standard:',
      'runs-on: macos-latest',
      'remote-verify-standard:',
      "needs.standard-first-run-vm-smoke-after-standard-only.result == 'success'",
      'remote-verify-full:',
      'node --experimental-strip-types scripts/prepare-release-assets.ts build-artifacts release-assets',
      'node --experimental-strip-types scripts/validate-release.ts release-assets',
      '--standard-artifacts-dir release-assets',
      'if [ "$RELEASE_MODE" = "new_release" ] || [ "$RELEASE_MODE" = "draft_candidate" ]; then',
      'npm run verify-remote-release',
      'draft_candidate',
      'uses: ./.github/workflows/full-first-install-release.yml',
      'uses: ./.github/workflows/opl-first-run-vm.yml',
      'standard-first-run-vm-smoke-after-standard-only:',
      'standard-first-run-vm-smoke-after-full:',
      'standard-vm-smoke-gate-after-full:',
      'Standard VM smoke must pass before Full publish, remote verification, Homebrew, operator evidence, or readiness aggregation can run',
      'stable-homebrew-tap-update:',
      'uses: ./.github/workflows/homebrew-tap-update.yml',
      'package_kind: app_standard',
      'homebrew-standard-first-run-vm-smoke:',
      'framework_ref: ${{ needs.publish-standard.outputs.framework_sha }}',
      "needs.release-preflight.outputs.homebrew_tap_update_required == 'true'",
      "needs.stable-homebrew-tap-update.result == 'success'",
      'full-first-run-vm-smoke:',
      "needs.full-first-run-vm-smoke.result == 'success'",
      'one-shot-app-installer-smoke:',
      'docker-webui-smoke:',
      'webui-ghcr-publish:',
      'operator-evidence-bundle-validation:',
      'release-evidence-bundle-${{ inputs.opl_version }}',
      'release-readiness-admission:',
      'Release readiness aggregation is blocked by failed, skipped, or missing required gates',
      'repository: gaofeng21cn/one-person-lab',
      'npm ci',
      'node --experimental-strip-types scripts/collect-release-evidence.ts',
      '--action-id developer_supervisor_refresh',
      '--execute-action',
      '--opl-bin "$GITHUB_WORKSPACE/one-person-lab/bin/opl"',
      '--evidence-source-dir "$full_source_dir"',
      '--evidence-source-dir "$standard_source_dir"',
      '--evidence-source-dir "$remote_source_dir"',
      'runtime_screenshot=$full_source_dir/artifacts/settings-pages/runtime-status.png',
      'manifest_args=(',
      'manifest_args+=(--require-conditional docker_webui_clean_vm_evidence)',
      'node --experimental-strip-types scripts/write-release-evidence-manifest.ts "${manifest_args[@]}"',
      'node --experimental-strip-types scripts/validate-release-evidence-bundle.ts',
      'validation_args+=(--require-conditional docker_webui_clean_vm_evidence)',
      '> evidence-validation-summary.json',
      "'operator-evidence-bundle-validation': '${{ needs.operator-evidence-bundle-validation.result }}'",
      'release-readiness-summary:',
      'scripts/summarize-release-readiness.ts',
      'release-readiness-summary.json',
      'shell_ref:',
      'shell_ref: ${{ inputs.shell_ref }}',
      'release_artifact_name: macos-build-arm64-dmg',
      'release_artifact_name: opl-full-first-install-dmg-${{ inputs.opl_version }}-mac-arm64',
      'actions/attest@v4',
      'subject-path: release-assets/*',
      'subject-path: full-package-artifacts/*',
      'subject-digest: ${{ steps.build_docker_webui.outputs.full_digest }}',
      'subject-digest: ${{ steps.build_docker_webui.outputs.slim_digest }}',
      'create-storage-record: false',
      'package_profile: standard',
      'package_profile: homebrew-standard',
      'package_profile: full',
      'release-addon-readiness-summary-${{ inputs.opl_version }}',
      'OPL_INSTALL_SCRIPT_URL: file://${{ github.workspace }}/one-person-lab/install.sh',
      'bash -n ./install-stable.sh',
      './install.sh --with-app --skip-modules',
      '--label "org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY}"',
      '--label "org.opencontainers.image.revision=${SHELL_SHA}"',
      'docker build',
      '-t "one-person-lab-webui:${{ inputs.opl_version }}"',
      '--build-arg OPL_WEBUI_IMAGE_PROFILE=webui-slim',
      '-t "one-person-lab-webui:${{ inputs.opl_version }}-slim"',
      'docker run --rm --entrypoint cat "one-person-lab-webui:${{ inputs.opl_version }}"',
      '/opt/opl/image-manifest.json',
      '/opt/opl/seed/metadata.json',
      'node --experimental-strip-types scripts/validate-webui-runtime-image.ts',
      '--expected-profile webui-full',
      '--expected-profile webui-slim',
      '/api/opl-runtime/startup-maintenance',
      '/api/opl-runtime/update-status',
      '/tmp/opl-webui-startup-maintenance.json',
      '/tmp/opl-webui-update-status.json',
      'node --experimental-strip-types scripts/validate-webui-runtime-smoke-receipts.ts',
      '/tmp/opl-webui-runtime-smoke-receipts-validation.json',
      'same_job_after_docker_webui_smoke',
      'repeated_docker_build: false',
      "image_profiles: ['webui-full', 'webui-slim']",
      'Download WebUI GHCR publish summary',
      'Verify WebUI GHCR publish summary',
      'docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin',
      'write_publish_summary "failed" "ghcr_write_package_denied"',
      'ghcr.io/${image_owner}/one-person-lab-webui',
      "required_actions_access_repository: 'gaofeng21cn/one-person-lab-app'",
      "source_repository: 'https://github.com/${GITHUB_REPOSITORY}'",
      '"${ghcr_image}:${{ inputs.opl_version }}"',
      '"${ghcr_image}:${{ inputs.opl_version }}-slim"',
      '"${ghcr_image}:stable"',
    ],
    forbidden: [
      'npm run gui:release',
      'packages:full-release',
      'repository: gaofeng21cn/one-person-lab-app',
      'write_mode: direct_commit',
      'peter-evans/create-pull-request',
      'pull-requests: read',
      'name: release-evidence-${{ inputs.opl_version }}',
      'npm run release:closeout --',
      'npm run release:actions-timing --',
      'release-closeout-${{ inputs.opl_version }}',
      'release-actions-timing-${{ inputs.opl_version }}',
    ],
  },
  {
    id: 'nightly_standard_release_workflow',
    file: '.github/workflows/nightly-standard-release.yml',
    required: [
      'name: OPL Nightly Standard Release',
      'schedule:',
      "cron: '17 18 * * *'",
      'uses: ./.github/workflows/_build-reusable.yml',
      'require_macos_gatekeeper: false',
      'runs-on: macos-latest',
      'name: macos-build-arm64',
      'node --experimental-strip-types scripts/prepare-release-assets.ts build-artifacts release-assets',
      'node --experimental-strip-types scripts/validate-release.ts release-assets',
      'prepare-nightly-release-notes:',
      'node --experimental-strip-types scripts/generate-release-notes.ts',
      'node --experimental-strip-types scripts/release-notes-ai-writer.ts',
      'OPL_RELEASE_NOTES_MODE: ai',
      'OPL_RELEASE_NOTES_PROVIDER: openai_compatible',
      "OPL_RELEASE_NOTES_CODEX_BASE_URL: ${{ vars.OPL_RELEASE_NOTES_CODEX_BASE_URL || 'https://gflabtoken.cn/v1' }}",
      "OPL_RELEASE_NOTES_MODEL: ${{ vars.OPL_RELEASE_NOTES_MODEL || 'gpt-5.4-mini' }}",
      'npm run release:notes:probe-ai',
      'OPL_RELEASE_NOTES_EVIDENCE_OUTPUT',
      '--evidence-output "$OPL_RELEASE_NOTES_EVIDENCE_OUTPUT"',
      '--evidence "$OPL_RELEASE_NOTES_EVIDENCE_OUTPUT"',
      'prepared-nightly-release-notes-${{ needs.resolve-nightly.outputs.version }}',
      'notes_file="prepared-nightly-release-notes/opl-nightly-notes.md"',
      '${{ runner.temp }}/opl-nightly-notes.md',
      '${{ runner.temp }}/opl-nightly-template-notes.md',
      'webui-ghcr-publish:',
      'remote_tag_sha="$(git ls-remote --tags origin "refs/tags/${OPL_RELEASE_TAG}"',
      'git tag -f "${OPL_RELEASE_TAG}" "$GITHUB_SHA"',
      'git push --force-with-lease="refs/tags/${OPL_RELEASE_TAG}:${remote_tag_sha}" origin "refs/tags/${OPL_RELEASE_TAG}"',
      'git push origin "refs/tags/${OPL_RELEASE_TAG}"',
      'release_title="One Person Lab ${OPL_RELEASE_TAG}"',
      '--title "$release_title"',
      '--prerelease',
      '--latest=false',
      'npm run verify-remote-release',
      '--label "org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY}"',
      '--label "org.opencontainers.image.revision=${SHELL_SHA}"',
      'docker build',
      '-t "one-person-lab-webui:${{ needs.resolve-nightly.outputs.version }}"',
      '--build-arg OPL_WEBUI_IMAGE_PROFILE=webui-slim',
      '-t "one-person-lab-webui:${{ needs.resolve-nightly.outputs.version }}-slim"',
      'docker run --rm --entrypoint cat "one-person-lab-webui:${{ needs.resolve-nightly.outputs.version }}"',
      '/opt/opl/image-manifest.json',
      '/opt/opl/seed/metadata.json',
      'node --experimental-strip-types scripts/validate-webui-runtime-image.ts',
      '--expected-profile webui-full',
      '--expected-profile webui-slim',
      'node --experimental-strip-types scripts/validate-webui-runtime-smoke-receipts.ts',
      'docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin',
      'write_publish_summary "failed" "ghcr_write_package_denied"',
      'ghcr.io/${image_owner}/one-person-lab-webui',
      "required_actions_access_repository: 'gaofeng21cn/one-person-lab-app'",
      "source_repository: 'https://github.com/${GITHUB_REPOSITORY}'",
      '"${ghcr_image}:${{ needs.resolve-nightly.outputs.version }}"',
      '"${ghcr_image}:${{ needs.resolve-nightly.outputs.version }}-slim"',
      '"${ghcr_image}:nightly"',
    ],
    forbidden: [
      'full-first-install-release.yml',
      'One-Person-Lab-Full',
      'nightly.${stamp}',
      'One Person Lab Nightly ${OPL_RELEASE_VERSION}',
      '--include-full-package',
      'include_full_package',
      'homebrew-tap-update:',
      'uses: ./.github/workflows/homebrew-tap-update.yml',
      'pull-requests: read',
      '"${ghcr_image}:stable"',
      '"${ghcr_image}:latest"',
      '--input "$template_notes_file"',
      'models: read',
      'OPL_RELEASE_NOTES_GITHUB_MODEL',
    ],
  },
  {
    id: 'webui_ghcr_release_workflow',
    file: '.github/workflows/webui-ghcr-release.yml',
    required: [
      'name: OPL WebUI GHCR Release',
      'workflow_dispatch:',
      'packages: write',
      'FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true',
      'repository: gaofeng21cn/opl-aion-shell',
      'Export WebUI release environment',
      'Prepare WebUI GHCR publish records',
      'Build WebUI Docker images',
      'Inspect and validate WebUI runtime images',
      'Smoke WebUI container runtime',
      'Tag WebUI GHCR images',
      'Publish WebUI GHCR tags',
      'bash scripts/webui-ghcr-release-step.sh prepare',
      'bash scripts/webui-ghcr-release-step.sh build',
      'bash scripts/webui-ghcr-release-step.sh inspect',
      'bash scripts/webui-ghcr-release-step.sh smoke',
      'bash scripts/webui-ghcr-release-step.sh tag',
      'bash scripts/webui-ghcr-release-step.sh publish',
      'WEBUI_CHANNEL_TAGS=stable',
    ],
    forbidden: [
      'uses: ./.github/workflows/opl-first-run-vm.yml',
      'uses: ./.github/workflows/_build-reusable.yml',
      'npm run release:publish',
      'gh release upload',
      '"${ghcr_image}:nightly"',
      'draft_candidate',
    ],
  },
  {
    id: 'docker_webui_clean_linux_vm_workflow',
    file: '.github/workflows/docker-webui-clean-linux-vm.yml',
    required: [
      'name: OPL Docker WebUI Clean Linux VM Smoke',
      'workflow_dispatch:',
      'runs-on: ubuntu-latest',
      'FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true',
      'ghcr.io/gaofeng21cn/one-person-lab-webui:stable',
      'artifact_name:',
      'docker-webui-clean-linux-vm-evidence',
      'node --experimental-strip-types scripts/docker-webui-smoke-gate.ts',
      '--gate clean_linux_vm',
      '--validate-result docker-webui-clean-linux-vm/docker-webui-smoke-gate-result.json',
      'docker compose -f docker-webui-clean-linux-vm/home/OnePersonLab/compose.yaml down --remove-orphans || true',
      'actions/upload-artifact@v7',
    ],
    forbidden: [
      '--gate existing_docker',
      '--gate clean_windows_vm',
      'packages: write',
      'OPENAI_API_KEY',
      'GHCR_TOKEN',
    ],
  },
  {
    id: 'docker_webui_clean_windows_vm_workflow',
    file: '.github/workflows/docker-webui-clean-windows-vm.yml',
    required: [
      'name: OPL Docker WebUI Clean Windows VM Smoke',
      'workflow_dispatch:',
      'runner_labels_json:',
      'runner_inventory_json:',
      '["self-hosted","Windows","X64","docker-webui-clean-vm"]',
      'runner-preflight:',
      'runs-on: ubuntu-latest',
      'workflow_dispatch_input',
      'RUNNER_INVENTORY_JSON',
      'repos/${process.env.GITHUB_REPOSITORY}/actions/runners',
      'runner_inventory_unreadable',
      'missing_clean_windows_self_hosted_runner',
      'docker-webui-clean-windows-vm-runner-blocker',
      'needs: runner-preflight',
      "if: ${{ needs.runner-preflight.result == 'success' }}",
      'runs-on: ${{ fromJSON(inputs.runner_labels_json) }}',
      'FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true',
      'ghcr.io/gaofeng21cn/one-person-lab-webui:stable',
      'artifact_name:',
      'docker-webui-clean-windows-vm-evidence',
      'powershell -ExecutionPolicy Bypass',
      '-File scripts/install-docker-webui.ps1',
      '-EvidenceDir windows-clean-evidence',
      '-EvidenceArchive windows-clean-evidence.zip',
      'node --experimental-strip-types scripts/docker-webui-smoke-gate.ts',
      '--gate clean_windows_vm',
      '--evidence windows-clean-evidence.zip',
      '--validate-result docker-webui-clean-windows-vm/docker-webui-smoke-gate-result.json',
      'actions/upload-artifact@v7',
      'docker compose -f $composePath down --remove-orphans',
    ],
    forbidden: [
      '--gate existing_docker',
      '--gate clean_linux_vm',
      'runs-on: windows-latest',
      'packages: write',
      'OPENAI_API_KEY',
      'GHCR_TOKEN',
    ],
  },
  {
    id: 'docker_webui_clean_windows_dispatch_helper',
    file: 'scripts/dispatch-docker-webui-clean-windows-smoke.ts',
    required: [
      'opl_docker_webui_clean_windows_dispatch_plan.v1',
      'runner_inventory_json',
      'missing_clean_windows_self_hosted_runner',
      'docker-webui-clean-windows-vm.yml',
      'actions/runners',
      'workflow',
      'run',
      '--execute',
    ],
  },
  {
    id: 'docker_webui_clean_windows_dispatch_npm_script',
    file: 'package.json',
    required: [
      'smoke:docker-webui:windows-clean-vm:dispatch',
      'scripts/dispatch-docker-webui-clean-windows-smoke.ts',
    ],
  },
  {
    id: 'docker_webui_clean_windows_runner_bootstrap_runbook',
    file: 'docs/delivery/install/docker-webui-smoke-gates.md',
    required: [
      'Clean Windows Runner Bootstrap',
      'self-hosted',
      'Windows',
      'X64',
      'docker-webui-clean-vm',
      'Docker Desktop',
      'WSL 2',
      'Settings -> Actions -> Runners -> New',
      'Keep the generated registration token out of docs',
      'npm run smoke:docker-webui:windows-clean-vm:dispatch -- --execute --json',
      'docker-webui-clean-windows-vm-evidence',
      'docker_webui_clean_windows_evidence_artifact',
      'docker-webui-clean-windows-vm-runner-blocker',
      'missing_clean_windows_self_hosted_runner',
      'runner_inventory_unreadable',
    ],
    forbidden: [
      'windows-latest runner is acceptable evidence',
      'registration token:',
      'OPENAI_API_KEY',
      'GHCR_TOKEN',
    ],
  },
  {
    id: 'webui_ghcr_release_helper',
    file: 'scripts/webui-ghcr-release-step.sh',
    required: [
      'docker build',
      '--label "org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY:?Set GITHUB_REPOSITORY.}"',
      '--label "org.opencontainers.image.revision=${SHELL_SHA}"',
      '-t "one-person-lab-webui:${OPL_VERSION}"',
      '--build-arg OPL_WEBUI_IMAGE_PROFILE=webui-slim',
      '-t "one-person-lab-webui:${OPL_VERSION}-slim"',
      'docker run --rm --entrypoint cat "one-person-lab-webui:${OPL_VERSION}"',
      '/opt/opl/image-manifest.json',
      '/opt/opl/seed/metadata.json',
      'node --experimental-strip-types scripts/validate-webui-runtime-image.ts',
      '--expected-profile webui-full',
      '--expected-profile webui-slim',
      'node --experimental-strip-types scripts/validate-webui-runtime-smoke-receipts.ts',
      'curl -fsS -D "$auth_headers" "http://127.0.0.1:${port}/api/auth/user"',
      'grep -q \'"success":[[:space:]]*true\' "$auth_body"',
      'grep -iq \'^set-cookie:\' "$auth_headers"',
      'docker login ghcr.io -u "${GITHUB_ACTOR:?Set GITHUB_ACTOR.}" --password-stdin',
      'write_publish_summary "failed" "ghcr_write_package_denied"',
      'ghcr.io/${image_owner}/one-person-lab-webui',
      '"${ghcr_image}:${OPL_VERSION}"',
      '"${ghcr_image}:${OPL_VERSION}-slim"',
      'WEBUI_CHANNEL_TAGS ||',
      '/tmp/opl-webui-runtime-smoke-receipts-validation.json',
      "required_actions_access_repository: 'gaofeng21cn/one-person-lab-app'",
      "source_repository: `https://github.com/${process.env.GITHUB_REPOSITORY}`",
      "shell_repository: 'https://github.com/gaofeng21cn/opl-aion-shell'",
      "image_profiles: ['webui-full', 'webui-slim']",
    ],
  },
  {
    id: 'release_notes_evidence_first',
    file: 'scripts/publish-release.ts',
    required: [
      'OPL_RELEASE_NOTES_MODE',
      'OPL_RELEASE_NOTES_EVIDENCE_OUTPUT',
      "process.env.OPL_RELEASE_NOTES_MODE || 'ai'",
      'buildReleaseNotesDocument',
      'buildAiReleaseNotesDocument',
      'buildReleaseNotesEvidence',
    ],
    forbidden: ['generate_release_notes: true'],
  },
  {
    id: 'release_notes_ai_provider_chain',
    file: 'scripts/release-notes-ai-writer.ts',
    required: [
      'OPL_RELEASE_NOTES_PROVIDER',
      'openai_compatible',
      '--probe-openai-compatible',
      'OPL_RELEASE_NOTES_AI_TIMEOUT_SECONDS',
      'OPL_RELEASE_NOTES_OPENAI_COMPATIBLE_BASE_URL',
      'OPL_RELEASE_NOTES_OPENAI_COMPATIBLE_API_KEY',
      'OPL_RELEASE_NOTES_CODEX_BASE_URL',
      'OPL_RELEASE_NOTES_CODEX_API_KEY',
      'OPL_RELEASE_NOTES_MODEL',
      'envValue',
      'OpenAI-compatible provider failed',
      'No online OpenAI-compatible release-note provider is configured.',
      'runCodexProvider',
      'validateAiReleaseNotes',
      'self-referential release-note copy',
      'opening paragraph is process-first',
      'missing opening user benefit paragraph before sections',
      'payload lines formatted as blockquotes',
      'developer memo terms before Technical details',
      'payload ref before Technical details',
      '## Technical details',
      'missing user-facing MAS/MAG/RCA role descriptions',
      'missing concrete runtime change detail',
      '## Install Stable',
      'missing Stable install command',
    ],
    forbidden: [],
  },
  {
    id: 'release_notes_agent_runtime_evidence',
    file: 'scripts/release-notes/payload.ts',
    required: [
      'buildAgentRuntimeChanges',
      'collectComponentChangeSubjects',
      'research automation and study workflow agent',
      'grant-writing and funding workflow agent',
      'visual deliverable, slide, and report graphics agent',
    ],
    forbidden: [],
  },
  {
    id: 'release_notes_agent_runtime_output',
    file: 'scripts/release-notes.ts',
    required: [
      'agent_runtime_changes',
      'buildAgentRuntimeChanges',
      'install_command',
      'install.sh | bash -s -- --stable-macos-install --yes',
    ],
    forbidden: [],
  },
  {
    id: 'homebrew_tap_boundary_script',
    file: 'scripts/update-homebrew-tap.ts',
    required: [
      'manifest_required: true',
      'checksum_required: true',
      'nightly_targets_only_for_nightly: true',
      'stable_promotion_from_nightly_allowed: false',
      'full_first_install_allowed: false',
      'full_first_install_allowed: true',
      'standard_updater_visible: false',
      'bundled_full_runtime_payload_allowed: true',
      'opl_packages_payload_allowed: false',
      'opl_packages_homebrew_allowed: false',
      'opl_packages_lifecycle_owner: one-person-lab',
      'forbidden_module_formulae: one-person-lab-modules,one-person-lab-modules-nightly',
      'publishes_or_pushes_remote: false',
      'app_full_first_install',
      'Nightly Homebrew tap updates may only update nightly formula/cask targets.',
      'Stable Homebrew tap updates must not use a nightly version.',
      'Full first-install Homebrew cask updates must stay on the stable channel.',
      'Full first-install Homebrew cask updates may only update Casks/one-person-lab-full.rb.',
      'Homebrew tap updates are App cask-only; OPL Packages are Framework-managed, not Homebrew formulae.',
      'must not reference Full first-install payloads',
    ],
    forbidden: [
      "from 'node:child_process'",
      'spawnSync(',
      'execSync(',
      'execFileSync(',
    ],
  },
  {
    id: 'homebrew_tap_package_scripts',
    file: 'package.json',
    required: [
      '"homebrew:tap:plan": "node --experimental-strip-types scripts/update-homebrew-tap.ts"',
      '"validate:homebrew-tap": "node --experimental-strip-types scripts/update-homebrew-tap.ts --self-check"',
      '"release:preflight": "node --experimental-strip-types scripts/validate-release-preflight.ts"',
      '"release:closeout": "node --experimental-strip-types scripts/closeout-release-run.ts"',
      '"release:actions-timing": "node --experimental-strip-types scripts/summarize-github-actions-timing.ts"',
      '"release:gate-reuse-plan": "node --experimental-strip-types scripts/plan-release-gate-reuse.ts"',
      '"release:readiness-summary": "node --experimental-strip-types scripts/summarize-release-readiness.ts"',
      '"release:full:prune-audit": "node --experimental-strip-types scripts/audit-full-runtime-prune-policy.ts"',
      '"release:candidate-record": "node --experimental-strip-types scripts/write-release-candidate-record.ts"',
      '"release:candidate-record:validate": "node --experimental-strip-types scripts/validate-release-candidate-record.ts --promote-ready"',
      '"release:candidate-record:status": "node --experimental-strip-types scripts/validate-release-candidate-record.ts --status"',
    ],
    forbidden: [],
  },
  {
    id: 'full_runtime_prune_policy_contract',
    file: 'contracts/full-runtime-prune-policy.json',
    required: [
      '"schema": "opl_full_runtime_prune_policy.v1"',
      '"id": "full_runtime_offline_first_install_slim_v1"',
      '"source": "Docker build context"',
      '"source": "npm pack dry-run"',
      '"source": "electron-builder application contents"',
      '"runtime_tree"',
      '"production_node_modules"',
      '"node_toolchain_global_packages"',
      '"app_bundle_staging"',
      '"runtime_assertions"',
      '"validation_examples"',
      '"audit_command": "npm run release:full:prune-audit -- --markdown"',
    ],
    forbidden: ['TODO', 'TBD'],
  },
  {
    id: 'full_runtime_prune_policy_audit_script',
    file: 'scripts/audit-full-runtime-prune-policy.ts',
    required: [
      'opl_full_runtime_prune_policy_audit.v1',
      'contracts/full-runtime-prune-policy.json',
      'validation_examples',
      'runtime_scan_diff',
      '--runtime-root',
      '--baseline',
      'collectRuntimeAssertions',
    ],
    forbidden: ['TODO', 'TBD'],
  },
  {
    id: 'release_actions_timing_script',
    file: 'scripts/summarize-github-actions-timing.ts',
    required: [
      'opl_github_actions_timing_summary.v1',
      'gh run view',
      '--json',
      'failed_or_cancelled_run_wall_seconds',
      'unaccounted_operator_seconds',
      'top_jobs',
      'top_steps',
    ],
    forbidden: ['gh run watch', 'gh run download'],
  },
  {
    id: 'release_closeout_script',
    file: 'scripts/closeout-release-run.ts',
    required: [
      'opl_release_closeout_summary.v1',
      'Agent orchestration wall time',
      'github_actions_workflow_wall_time',
      'agent_orchestration_wall_time_seconds',
      'downloads_large_artifacts: false',
      'forbiddenLargeArtifactPatterns',
      'workflow_default_release_summary',
      'release-candidate-record-${options.version}',
      'release-readiness-summary-${options.version}',
      'remote-release-verification-${options.version}',
      'validate-release-candidate-record.ts',
      '--promote-ready',
      'owner_needed_release_owner_resolution',
      'release_owner_verdict_ref',
      'release_owner_receipt_ref',
      'release_owner_typed_blocker_ref',
      'gh run view',
      'gh run download',
      'inspect_logs_only_after',
    ],
    forbidden: [
      'One-Person-Lab-*.dmg',
      'One-Person-Lab-Full-*.dmg',
    ],
  },
  {
    id: 'release_candidate_record_script',
    file: 'scripts/write-release-candidate-record.ts',
    required: [
      'opl_release_candidate_record.v1',
      'ready_to_promote',
      'blocked',
      'diagnostic_only',
      'Only ready_to_promote candidate records may publish a Stable draft release.',
      'release_owner_verdict',
      'release_owner_typed_blocker_ref',
      'release_owner_receipt_ref',
      'install_evidence_ref',
      'owner_resolution_ref_shapes',
      '--allow-blocked',
    ],
    forbidden: ['TODO', 'TBD'],
  },
  {
    id: 'release_gate_reuse_plan_script',
    file: 'scripts/plan-release-gate-reuse.ts',
    required: [
      'opl_release_gate_reuse_plan.v1',
      'opl_release_gate_reuse_digest.v1',
      'reuse_plan_can_skip_release_gate_by_itself: false',
      'workflow_must_explicitly_consume_reuse_allowed_decision: true',
      'remote verified asset name/size/sha256 set changed',
      'previous candidate status is',
      'ready_to_promote',
      'current preflight did not resolve shell ref sha',
      'current preflight app commit',
      'does not match requested shell ref',
      'does not match requested framework ref',
      'same version, release mode, inputs, app commit, resolved refs, remote asset digests, and previous passed gate evidence',
      'reuse_digest',
      'cohort',
    ],
    forbidden: ['TODO', 'TBD'],
  },
  {
    id: 'release_candidate_record_validator_script',
    file: 'scripts/validate-release-candidate-record.ts',
    required: [
      'opl_release_candidate_record.v1',
      'ready_to_promote',
      'decision.can_promote',
      'release_owner_verdict',
      'release_ready_claim',
      'release_owner_verdict_recorded',
      'release_owner_receipt_ref',
      'blocked_reasons',
      '--promote-ready',
      '--status',
    ],
    forbidden: ['TODO', 'TBD'],
  },
  {
    id: 'release_preflight_script',
    file: 'scripts/validate-release-preflight.ts',
    required: [
      'opl_release_preflight.v1',
      'release-preflight-summary.json',
      'release-preflight-summary.md',
      'OPL_HOMEBREW_TAP_TOKEN_PRESENT',
      'refresh_existing requires GitHub Release',
      'release_target',
      'tap_update_required',
      'desktop_release_promote_after_publish',
      'workflow_preflight_shape',
      'release_plan',
      'release_refs',
      'codex_package_metadata',
      '@openai/codex@latest',
      '-darwin-arm64',
      'homebrew_tap_token',
      'macos_local_authorization',
    ],
    forbidden: ['TODO', 'TBD'],
  },
  {
    id: 'homebrew_tap_update_workflow',
    file: '.github/workflows/homebrew-tap-update.yml',
    required: [
      'name: OPL Homebrew Tap Update',
      'workflow_call:',
      'OPL_HOMEBREW_TAP_TOKEN',
      'gaofeng21cn/homebrew-one-person-lab',
      'Casks/one-person-lab.rb',
      'Casks/one-person-lab-nightly.rb',
      'Casks/one-person-lab-full.rb',
      'gh release view "$tag"',
      '--json tagName,isDraft,isPrerelease,assets',
      'Homebrew tap updates are App cask-only; OPL Packages are Framework-managed.',
      'GitHub Release asset ${asset.name} must expose a sha256 digest.',
      'Homebrew tap updates must not read draft GitHub Releases.',
      'Homebrew tap updates must read assets from gaofeng21cn/one-person-lab-app',
      'One-Person-Lab-Full-${version}-mac-arm64.dmg',
      'opl-release-manifest.json',
      'standard-local-authorization-policy.json',
      'Full first-install Homebrew cask updates must stay on the stable channel.',
      'node --experimental-strip-types scripts/update-homebrew-tap.ts',
      '--remote-write-mode "direct_commit"',
      'OPL_HOMEBREW_TAP_TOKEN is required for Homebrew tap direct commits.',
      'git -C homebrew-tap push origin HEAD:main',
      'group: opl-homebrew-tap-${{ inputs.channel }}-${{ inputs.opl_version }}',
      'Homebrew tap push failed on attempt ${attempt}; fetching and rebasing before retry.',
      'git -C homebrew-tap fetch origin main',
      'git -C homebrew-tap rebase origin/main',
      'Homebrew tap direct commit push failed after rebase retries.',
    ],
    forbidden: [
      'gh release upload',
      'peter-evans/create-pull-request',
      'inputs.write_mode',
      'pull-requests: read',
      'pull_request',
    ],
  },
  {
    id: 'reusable_build_gatekeeper_policy',
    file: '.github/workflows/_build-reusable.yml',
    required: [
      'macos-signing-preflight:',
      'name: macOS release signing preflight',
      'macOS release signing preflight failed',
      'Missing GitHub Actions secrets:',
      'require_macos_gatekeeper:',
      'OPL_REQUIRE_MACOS_GATEKEEPER',
      'opl_flow_ref:',
      'default: 5ae0625f5240a13fa820b4c92362f1d06bdce857',
      'name: Checkout OPL Flow policy source',
      'ref: ${{ inputs.opl_flow_ref }}',
      'OPL_FLOW_WORKFLOW_POLICY: ${{ github.workspace }}/opl-flow/contracts/workflow-policy.json',
      'OPL_FULL_OPL_FLOW_ROOT: ${{ github.workspace }}/opl-flow',
      'Write macOS Stable local authorization policy',
      'Ensure macOS standard updater ZIP distributable',
      'expected_zip="One-Person-Lab-${OPL_RELEASE_VERSION}-mac-${target_arch}.zip"',
      'expected_zip_blockmap="${expected_zip}.blockmap"',
      'Missing standard updater ZIP',
      'Missing standard updater ZIP blockmap',
      '--mac dmg zip',
      '--prepackaged "$app_path"',
      'grep -q "$expected_zip" "$metadata"',
      'spctl --assess --type execute --verbose=4 "$app_path"',
      'standard-local-authorization-policy.json',
      'standard-gatekeeper-launch-policy.json',
      '--package-kind app_standard',
    ],
    forbidden: [],
  },
  {
    id: 'release_asset_local_authorization_verifiers',
    file: 'scripts/verify-remote-release-assets.ts',
    required: [
      'standard-local-authorization-policy.json',
      'full-local-authorization-policy.json',
      'full-runtime-currentness-probe.json',
      'full-runtime-native-trust.json',
      'assertStableLocalAuthorizationPolicy',
      'assertStandardUpdaterAppBundleTrust',
      'standardUpdaterAppBundleTrust',
      'standard_updater_app_bundle_trust',
      'apple_developer_id_required',
      'gatekeeper_required',
      'local_authorization_policy',
      'TeamIdentifier',
      'Signature',
      'adhoc',
      'assertFullRuntimeNativeTrust',
      'spctl_status',
      'codesign_status',
      'failed_allowed_unsigned',
      'local_authorized_unsigned',
    ],
    forbidden: [],
  },
  {
    id: 'first_run_vm_local_authorization_policy',
    file: path.relative(appRoot, path.join(shellPaths.shellRoot, 'scripts/opl-first-run-vm-smoke.mjs')),
    required: [
      "xattr', ['-dr', 'com.apple.quarantine', targetApp]",
      'gatekeeper-launch-policy.json',
      'gatekeeper_required: false',
      'quarantine_removal_required: true',
      'local_authorization_status: localAuthorizationStatus',
      "'rejected_allowed_unsigned'",
      "'failed_allowed_unsigned'",
      'countQuarantineAttributes(appPath)',
      'quarantine_attribute_count: quarantineAttributeCount',
      'if (quarantineAttributeCount !== 0)',
    ],
    forbidden: [
      'if (codesign.status !== 0)',
      'if (codesign.status !== 0 || spctl.status !== 0)',
      'Gatekeeper launch policy rejected the packaged app before first launch.',
    ],
  },
  {
    id: 'first_run_vm_profile_aware_assistant_smoke',
    file: path.relative(appRoot, path.join(shellPaths.shellRoot, 'scripts/opl-first-run-vm-smoke.mjs')),
    required: [
      'homeAssistantBlockedReadinessExpression',
      "options.runtimeProfile !== 'full'",
      "verification_mode: 'launch_gate'",
      "verification_mode: 'route_receipt'",
      'home-starter-${id}',
      'assistant_launch_gates_checked',
      'not_applicable_standard',
    ],
    forbidden: [],
  },
  {
    id: 'one_shot_unsigned_local_authorization',
    file: 'install.sh',
    required: [
      '--stable-macos-install',
      'STABLE_MACOS_PACKAGE_PROFILE=${OPL_STABLE_MACOS_PACKAGE_PROFILE:-full}',
      'resolve_latest_release_tag()',
      'release_asset_name()',
      'download_or_use_dmg()',
      'copy_app_from_dmg()',
      'stable_macos_install()',
      'hdiutil attach -nobrowse -readonly',
      'ditto "$source_app" "$OPL_LOCAL_APP_PATH"',
      'run_with_sudo_fallback',
      '--authorize-local-app-only',
      '--authorize-local-app',
      '--app-path',
      'OPL_LOCAL_APP_PATH=${OPL_LOCAL_APP_PATH:-/Applications/One Person Lab.app}',
      'Type "authorize" to continue',
      'xattr -dr com.apple.quarantine "$OPL_LOCAL_APP_PATH"',
      'codesign --verify --deep --strict --verbose=2 "$OPL_LOCAL_APP_PATH"',
      'spctl --assess --type execute --verbose=4 "$OPL_LOCAL_APP_PATH"',
      'quarantine_before',
      'quarantine_after',
      'Stable macOS install',
    ],
    forbidden: [],
  },
  {
    id: 'short_stable_macos_installer',
    file: 'install-stable.sh',
    required: [
      'OPL_APP_INSTALLER_URL=',
      'https://raw.githubusercontent.com/gaofeng21cn/one-person-lab-app/main/install.sh',
      'curl -fsSL "$installer_url" | bash -s -- --stable-macos-install --yes "$@"',
    ],
    forbidden: [],
  },
  {
    id: 'install_exposure_unsigned_and_temporal_policy',
    file: 'contracts/app-install-exposure-policy.json',
    required: [
      '"surface": "stable_local_authorized_macos_install"',
      '"entrypoint": "install.sh --stable-macos-install --yes"',
      '"compatibility_entrypoints"',
      '"install-stable.sh"',
      '"default_package_profile": "full"',
      '"hdiutil attach -nobrowse -readonly"',
      '"ditto"',
      '"open"',
      '"surface": "unsigned_local_app_authorization"',
      '"entrypoint": "install.sh --authorize-local-app-only"',
      '"stable_release_path": true',
      '"xattr -dr com.apple.quarantine"',
      '"codesign --verify --deep --strict --verbose=2"',
      '"spctl --assess --type execute --verbose=4"',
      '"auto_configuration_entrypoints"',
      '"opl system startup-maintenance"',
      '"must_export_local_defaults_before_provider_checks": true',
      '"must_surface_service_worker_and_dependency_diagnostics": true',
      '"must_not_block_ready_to_launch_on_worker_residency": true',
      '"must_fail_closed_when_packaged_temporal_payload_is_missing": true',
    ],
    forbidden: [],
  },
  {
    id: 'desktop_release_evidence_notes',
    file: '.github/workflows/desktop-release.yml',
    required: [
      'GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}',
      'GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}',
      'prepare-standard-release-notes:',
      'prepare-full-release-notes:',
      'OPL_RELEASE_NOTES_MODE: template',
      '--input standard-release-notes-template.md',
      '--input full-release-notes-template.md',
      'OPL_RELEASE_NOTES_FILE: prepared-standard-release-notes/standard-release-notes.md',
      'OPL_RELEASE_NOTES_FILE: prepared-full-release-notes/full-release-notes.md',
      '--release-notes-file "$OPL_RELEASE_NOTES_FILE"',
      'prepared-standard-release-notes-${{ inputs.opl_version }}',
      'prepared-full-release-notes-${{ inputs.opl_version }}',
    ],
    forbidden: [
      'Install Codex release-note writer',
      'Configure Codex release-note writer',
      'scripts/setup-release-notes-codex-config.ts',
      'models: read',
      'OPL_RELEASE_NOTES_GITHUB_MODEL',
    ],
  },
  {
    id: 'remote_release_verification_workflow_uses_app_script',
    file: '.github/workflows/release-verify-remote.yml',
    required: ['runs-on: macos-latest', 'npm run verify-remote-release', '--include-full-package'],
    forbidden: ['npm run gui:release', 'packages:full-release', 'repository: gaofeng21cn/one-person-lab-app'],
  },
  {
    id: 'non_release_validation_workflow',
    file: '.github/workflows/non-release-validation.yml',
    required: [
      'name: OPL Non-Release Validation',
      'push:',
      'branches:',
      '- main',
      'workflow_dispatch:',
      'permissions:',
      'contents: read',
      'name: App release-boundary tests',
      'runs-on: ubuntu-latest',
      'actions/checkout@v6',
      'uses: ./.github/actions/setup-active-shell-deps',
      'install-dependencies: \'false\'',
      'name: Checkout OPL Flow policy source',
      'ref: 5ae0625f5240a13fa820b4c92362f1d06bdce857',
      'OPL_FLOW_WORKFLOW_POLICY: ${{ github.workspace }}/opl-flow/contracts/workflow-policy.json',
      'OPL_FULL_OPL_FLOW_ROOT: ${{ github.workspace }}/opl-flow',
      'npm run test:release-boundary',
      'npm run validate:release-boundary',
    ],
    forbidden: [
      'contents: write',
      'packages: write',
      'actions: write',
      'gh release',
      'npm run release:publish',
      'npm run release:full',
      'npm run build',
      'npm run package',
      'uses: ./.github/workflows/_build-reusable.yml',
      'uses: ./.github/workflows/full-first-install-release.yml',
      'uses: ./.github/workflows/desktop-release.yml',
    ],
  },
  {
    id: 'full_runtime_cache_warmup_reuses_full_workflow',
    file: '.github/workflows/full-runtime-cache-warmup.yml',
    required: [
      'uses: ./.github/workflows/full-first-install-release.yml',
      'publish_to_release: false',
      'force_rebuild_runtime_cache:',
    ],
    forbidden: ['npm run gui:release', 'packages:full-release', 'gh release upload'],
  },
  {
    id: 'desktop_release_promote_verifies_before_publish',
    file: '.github/workflows/desktop-release-promote.yml',
    required: [
      'release_run_id:',
      'Download release candidate record',
      'release-candidate-record-${{ inputs.opl_version }}',
      'release-candidate-record.json',
      'npm run release:candidate-record:validate',
      'Resolve release cohort refs',
      'record?.inputs?.framework_ref',
      'framework_ref: ${{ needs.promote.outputs.framework_ref }}',
      'npm run verify-remote-release',
      'runs-on: macos-latest',
      'gh release edit "v${OPL_RELEASE_VERSION}"',
      '--draft=false',
      'Verify published release readback',
      'gh release view "$tag"',
      '--json tagName,isDraft,isPrerelease,publishedAt,assets',
      'gh release list',
      '--json tagName,isLatest,isDraft,isPrerelease,publishedAt',
      'git ls-remote --exit-code --tags origin "refs/tags/${tag}"',
      'Promoted release is still a draft.',
      'Promoted Stable release is not marked latest.',
      'Published release ${tag} did not become readable with a matching tag before Homebrew tap update.',
      'homebrew-standard-first-run-vm-smoke:',
      "needs.stable-homebrew-tap-update.result == 'success'",
    ],
    forbidden: [
      'npm run gui:release',
      'packages:full-release',
      'repository: gaofeng21cn/one-person-lab-app',
      "needs.stable-homebrew-tap-update.result == 'success' && (!inputs.include_full_package || needs.full-homebrew-tap-update.result == 'success')",
    ],
  },
  {
    id: 'desktop_release_cleanup_drafts_workflow',
    file: '.github/workflows/desktop-release-cleanup-drafts.yml',
    required: [
      'name: OPL Desktop Release Cleanup Drafts',
      'workflow_dispatch:',
      'dry_run:',
      'npm run release:cleanup-drafts',
      '--summary-path release-draft-cleanup-summary.json',
      '--execute',
      '--dry-run',
      'actions/upload-artifact@v7',
    ],
    forbidden: ['One-Person-Lab-*.dmg', 'gh release download', 'actions/download-artifact'],
  },
  {
    id: 'desktop_release_diagnostics_workflow',
    file: '.github/workflows/desktop-release-diagnostics.yml',
    required: [
      'name: OPL Desktop Release Diagnostics',
      'workflow_dispatch:',
      'release_run_id:',
      'run_vm_diagnostic:',
      'build_standard_artifact:',
      'release_dmg_url:',
      'release_artifact_name:',
      'release_artifact_run_id:',
      'package_profile:',
      'diagnostic_scope:',
      'default: bootstrap_only',
      'inputs.diagnostic_scope',
      'temporary-standard-artifact',
      'inputs.release_artifact_run_id',
      'release-asset',
      "inputs.run_vm_diagnostic && 'vm' || 'metadata'",
      'permissions:',
      'actions: read',
      'contents: read',
      'diagnostic-inputs:',
      'Validate diagnostic workflow inputs',
      'build_standard_artifact only supports package_profile=standard',
      'build_standard_artifact must not be combined with release_dmg_url, release_artifact_name, or release_artifact_run_id',
      'npm run release:closeout --',
      '--artifact-profile diagnostics',
      'npm run release:actions-timing --',
      'standard-dmg-diagnostic-artifact:',
      'Build temporary standard DMG diagnostic artifact',
      'upload_installers_only: true',
      'vm-harness-diagnostics-standard-artifact:',
      'Run first-run VM diagnostic harness for temporary standard artifact',
      "inputs.build_standard_artifact && needs.diagnostic-inputs.result == 'success' && needs.standard-dmg-diagnostic-artifact.result == 'success'",
      'vm-harness-diagnostics-release-asset:',
      'Run first-run VM diagnostic harness for release asset',
      "!inputs.build_standard_artifact && needs.diagnostic-inputs.result == 'success'",
      'release_artifact_name: macos-build-arm64-dmg',
      'release_artifact_run_id: ${{ github.run_id }}',
      'release_artifact_name: ${{ inputs.release_artifact_name }}',
      "release_artifact_run_id: ${{ inputs.release_artifact_run_id != '' && inputs.release_artifact_run_id || inputs.release_run_id }}",
      'diagnostic_scope: ${{ inputs.diagnostic_scope }}',
      'uses: ./.github/workflows/opl-first-run-vm.yml',
      'release-diagnostics-${{ inputs.opl_version }}',
      'actions/upload-artifact@v7',
    ],
    forbidden: ['contents: write', 'packages: write', 'full-first-install-release', 'gh release edit', 'gh release upload', 'npm run release:publish'],
  },
];
